// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA12stJeKfC9F_Tncva16xIeTA1aaXXMXc',
    appId: '1:1038034237584:web:0c6ca19cec8c94d1690015',
    messagingSenderId: '1038034237584',
    projectId: 'netube-45c43',
    authDomain: 'netube-45c43.firebaseapp.com',
    storageBucket: 'netube-45c43.firebasestorage.app',
    measurementId: 'G-3N60L5JRYQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmVfSXu1wcrpuvGlnKQQ0tka-FMM3pj68',
    appId: '1:1038034237584:android:ad08553c98fe6794690015',
    messagingSenderId: '1038034237584',
    projectId: 'netube-45c43',
    storageBucket: 'netube-45c43.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoGAs3Q8UN4ynJSPI9F4OlCEnyf49u68k',
    appId: '1:1038034237584:ios:b3e0c4714965ade9690015',
    messagingSenderId: '1038034237584',
    projectId: 'netube-45c43',
    storageBucket: 'netube-45c43.firebasestorage.app',
    iosBundleId: 'com.example.netube',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoGAs3Q8UN4ynJSPI9F4OlCEnyf49u68k',
    appId: '1:1038034237584:ios:b3e0c4714965ade9690015',
    messagingSenderId: '1038034237584',
    projectId: 'netube-45c43',
    storageBucket: 'netube-45c43.firebasestorage.app',
    iosBundleId: 'com.example.netube',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA12stJeKfC9F_Tncva16xIeTA1aaXXMXc',
    appId: '1:1038034237584:web:e1ef1944a76033a4690015',
    messagingSenderId: '1038034237584',
    projectId: 'netube-45c43',
    authDomain: 'netube-45c43.firebaseapp.com',
    storageBucket: 'netube-45c43.firebasestorage.app',
    measurementId: 'G-D3N75NVH9S',
  );
}
